import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import { useController } from "../store/controller";

export function PairingScreen() {
  const pair = useController((s) => s.pair); const [host, setHost] = useState("http://127.0.0.1:8787"); const [code, setCode] = useState(""); const [scanning, setScanning] = useState(false); const [permission, requestPermission] = useCameraPermissions();
  const submit = async () => { try { await pair(host, code); } catch (error) { Alert.alert("Pairing failed", error instanceof Error ? error.message : String(error)); } };
  const scan = async () => { if (!permission?.granted && !(await requestPermission()).granted) return; setScanning(true); };
  if (scanning) return <View style={styles.root}><CameraView style={StyleSheet.absoluteFill} barcodeScannerSettings={{ barcodeTypes: ["qr"] }} onBarcodeScanned={({ data }) => { try { const parsed = JSON.parse(data); setHost(parsed.host); setCode(parsed.pairingCode); setScanning(false); } catch { Alert.alert("Invalid QR code"); } }} /><Pressable style={styles.cancel} onPress={() => setScanning(false)}><Text style={styles.buttonText}>Cancel</Text></Pressable></View>;
  return <View style={styles.root}><View style={styles.card}><Text style={styles.logo}>CODEX MICRO</Text><Text style={styles.hint}>Pair this controller with the desktop Companion</Text><TextInput value={host} onChangeText={setHost} autoCapitalize="none" style={styles.input} placeholder="http://desktop:8787" placeholderTextColor="#60717c" /><TextInput value={code} onChangeText={setCode} style={styles.input} placeholder="000-000" keyboardType="number-pad" placeholderTextColor="#60717c" /><Pressable style={styles.primary} onPress={submit}><Text style={styles.buttonText}>PAIR</Text></Pressable><Pressable style={styles.secondary} onPress={scan}><Text style={styles.buttonText}>SCAN QR</Text></Pressable><Text style={styles.note}>For USB debugging run: adb reverse tcp:8787 tcp:8787</Text></View></View>;
}

const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#050a0e", alignItems: "center", justifyContent: "center" }, card: { width: "88%", maxWidth: 460, padding: 28, borderRadius: 24, backgroundColor: "#0b141b", borderWidth: 1, borderColor: "#19313e" }, logo: { color: "#5de1ff", fontSize: 28, fontWeight: "900", letterSpacing: 3 }, hint: { color: "#8da2ad", marginVertical: 18 }, input: { color: "white", backgroundColor: "#071018", borderColor: "#1c3b4a", borderWidth: 1, borderRadius: 12, padding: 14, marginBottom: 12 }, primary: { backgroundColor: "#087d9d", padding: 15, borderRadius: 12, alignItems: "center" }, secondary: { backgroundColor: "#142731", padding: 15, borderRadius: 12, alignItems: "center", marginTop: 10 }, buttonText: { color: "white", fontWeight: "800" }, note: { color: "#60717c", fontSize: 12, marginTop: 18 }, cancel: { position: "absolute", bottom: 40, backgroundColor: "#15252e", padding: 16, borderRadius: 12 } });
